'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ConfigService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/ConfigService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ConfigService.IConfig")>  _
    Public Interface IConfig
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IConfig/GetData", ReplyAction:="http://tempuri.org/IConfig/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IConfig/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IConfig/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As ConfigService.CompositeType) As ConfigService.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IConfig/GetConfigCollection", ReplyAction:="http://tempuri.org/IConfig/GetConfigCollectionResponse")>  _
        Function GetConfigCollection(ByVal ConfigName As String) As System.Collections.SortedList
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IConfig/SetConfigCollection", ReplyAction:="http://tempuri.org/IConfig/SetConfigCollectionResponse")>  _
        Sub SetConfigCollection(ByVal ConfigName As String, ByVal Configuration As System.Collections.SortedList)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IConfig/LoadMasterConfig", ReplyAction:="http://tempuri.org/IConfig/LoadMasterConfigResponse")>  _
        Sub LoadMasterConfig()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IConfigChannel
        Inherits ConfigService.IConfig, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ConfigClient
        Inherits System.ServiceModel.ClientBase(Of ConfigService.IConfig)
        Implements ConfigService.IConfig
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements ConfigService.IConfig.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As ConfigService.CompositeType) As ConfigService.CompositeType Implements ConfigService.IConfig.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetConfigCollection(ByVal ConfigName As String) As System.Collections.SortedList Implements ConfigService.IConfig.GetConfigCollection
            Return MyBase.Channel.GetConfigCollection(ConfigName)
        End Function
        
        Public Sub SetConfigCollection(ByVal ConfigName As String, ByVal Configuration As System.Collections.SortedList) Implements ConfigService.IConfig.SetConfigCollection
            MyBase.Channel.SetConfigCollection(ConfigName, Configuration)
        End Sub
        
        Public Sub LoadMasterConfig() Implements ConfigService.IConfig.LoadMasterConfig
            MyBase.Channel.LoadMasterConfig
        End Sub
    End Class
End Namespace
